name: Terraform Destroy with GitHub Actions

on: 
  workflow_dispatch:
    branches:
      - deploy
      

env:
  PROJECT_DIR: projects/ecs-kinesis-timestream
  PROJECT_NAME: "ecs-kinesis-timestream"
  ENV: "pdn"
        

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
            
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.4.6
            terraform_wrapper: false
            
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Set up AWS CLI configuration
          run: |
            mkdir -p $HOME/.aws
            echo "[default]" >> $HOME/.aws/credentials
            echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
            echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
            echo "[default]" >> $HOME/.aws/config
            echo "region=${{ secrets.AWS_REGION }}" >> $HOME/.aws/config


        - name: Download terraform.tfstate
          uses: actions/download-artifact@v3
          with:
              name: terraform.tfstate

        - name: validate project structure
          run: tree

        - name: Terraform Init
          run: |
            cd ${{ env.PROJECT_DIR }}/terraform
            terraform init

        - name: Terraform destroy
          id: terraform-destroy
          run: |
            cd ${{ env.PROJECT_DIR }}/terraform
            terraform destroy -auto-approve